spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: darkroot
    password: '@darKrOot3646'
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
server:
  port: 9090
  error:
    include-stacktrace: never